### ISSUE TITLE
Can't capture message on Android (NS8)

### ISSUE THREAD

**Issue by res0** [nativescript-community/sentry#6]
### Which platform(s) does your issue occur on?
- Android emulator (Pixel 4 API 30)

### Please, provide the following version numbers that your issue occurs with:
- CLI: 8.1.5
- Cross-platform modules: 8.1.1
- Runtime(s): Android 8.1.1

### Please, tell us how to recreate the issue in as much detail as possible. 
When I try to run `Sentry.captureMessage('Hello Sentry!')` on Android emulator, it gives me this error in console:
```
JS: error sending sentry event TypeError: Cannot read property 'flushSendEvent' of undefined TypeError: Cannot read property 'flushSendEvent' of undefined
JS:     at file: app/webpack:/Project/node_modules/@nativescript-community/sentry/nssentry.android.js:158:0
```
However, on iOS Simulator it works.

**Comment by res0** [comment]
@farfromrefug I called it just like this:
```
    Sentry.init({ 
        dsn: "DSN"
    })
```

**Comment by farfromrefug** [comment]
@res0 can you try version 3.0.2?

**Comment by res0** [comment]
hey @farfromrefug, you're very fast! :D however, it still shows that error, but it worked when I provided `dist` :)

and I also needed to update `node_modules/@nativescript-community/sentry/platforms/android/buildscript.gradle` to use mavenCentral as it couldn't find it on just google:
```
repositories {
    google()
    mavenCentral()
}
dependencies {
    classpath 'io.sentry:sentry-android-gradle-plugin:2.1.5'
}
```

Thank you very much for what you're doing for the NS community!

**Comment by sebj54** [comment]
Hi!

i just had a similar problem and I can confirm that you need to edit `buildscript.gradle` like @res0 suggested.

Error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all artifacts for configuration ':app:classpath'.
   > Could not find io.sentry:sentry-android-gradle-plugin:2.1.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/sentry/sentry-android-gradle-plugin/2.1.5/sentry-android-gradle-plugin-2.1.5.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Unable to apply changes on device: 08f8d37c0504. Error is: Command ./gradlew failed with exit code 1.
```

Fix: 

```diff

  repositories {
      google()
+     mavenCentral()
  }
  dependencies {
      classpath 'io.sentry:sentry-android-gradle-plugin:2.1.5'
  }

```

**Comment by farfromrefug** [comment]
@sebj54 @res0 thank you both for the reports ! 3.0.3 should fix both errors

**Comment by sebj54** [comment]
Thanks for the quick fix! 

I just updated the plugin and it now works as expected :)

**Comment by res0** [comment]
Thank you very much, works well now! Closing this issue as it's been resolved :)
