### ISSUE TITLE
Version 3.1.0 incompatible with NativeScript 8.1?

### ISSUE THREAD

**Issue by sebj54** [nativescript-community/sentry#7]
Hi there! With latest version, I cannot build for Android:

Excerpt of build log:

```
Building project...
Gradle build...
         + applying user-defined buildscript from dependency /Users/sebjean/projects/my-project/node_modules/@nativescript-community/sentry/platforms/android/buildscript.gradle
         + setting applicationId

Script '/Users/sebjean/projects/my-project/node_modules/@nativescript-community/sentry/platforms/android/include.gradle' line: 2
A problem occurred evaluating script.
com.android.build.api.variant.AndroidComponentsExtension

Unable to apply changes on device: 08f8d37c0504. Error is: Command ./gradlew failed with exit code 1.
```

### Which platform(s) does your issue occur on?
- Android 

### Please, provide the following version numbers that your issue occurs with:

- CLI: `8.1.5`
- Cross-platform modules: `@nativescript/core 8.1.5`
- Runtime(s): `@nativescript/android 8.1.1`
- Plugin(s): 
- 
```
my-project@2.0.8 /Users/sebjean/projects/my-project
├── @nativescript-community/ble@3.1.6
├── @nativescript-community/insomnia@2.0.2
├── @nativescript-community/perms@2.2.5
├── @nativescript-community/sentry@3.1.0
├── @nativescript/android@8.1.1
├── @nativescript/core@8.1.5
├── @nativescript/datetimepicker@2.1.9
├── @nativescript/eslint-plugin@0.0.4
├── @nativescript/firebase@11.1.3
├── @nativescript/ios@8.1.0
├── @nativescript/iqkeyboardmanager@2.0.0
├── @nativescript/localize@5.0.4
├── @nativescript/theme@3.0.2
├── @nativescript/webpack@5.0.4
├── @nstudio/nativescript-shimmer@1.0.7
├── @sentry/webpack-plugin@1.18.7
├── @sergeymell/nativescript-svg@1.1.2
├── @triniwiz/nativescript-stripe@7.0.1
├── @triniwiz/nativescript-toasty@4.1.3
├── aes-js@3.1.2
├── debounce@1.2.1
├── dotenv@10.0.0
├── eslint-config-standard@16.0.3
├── eslint-plugin-import@2.25.4
├── eslint-plugin-node@11.1.0
├── eslint-plugin-promise@5.2.0
├── eslint-plugin-vue@7.20.0
├── eslint@7.32.0
├── js-easing-functions@1.0.3
├── nativescript-exit@1.0.1
├── nativescript-extendedinfo@1.0.11
├── nativescript-ui-gauge@8.0.1
├── nativescript-ui-listview@10.0.2
├── nativescript-vibrate@4.0.1
├── nativescript-vue-template-compiler@2.9.0
├── nativescript-vue@2.9.0
└── vuex@3.6.2
```

### Please, tell us how to recreate the issue in as much detail as possible. 

Update `@nativescript/community` to version 3.1.0. Run `ns debug android` (or any build command for Android).

I noticed the demo uses `@nativescript/android 8.2.0-alpha`. Maybe the Gradle plugin uses something from Android 12? Unfortuantely I can update to Nativescript Android 8.2.0 because some of my plugins are incompatible (especially @nativescript/firebase).

Do you know if I can use latest version of this plugin with my Nativescript version? Maybe by tweaking my Gradle file?

Thanks for your help

**Comment by farfromrefug** [comment]
@sebj54 no you dont need "core" alpha i think. But you might be needing runtime alpha as indeed there is a gradle 7 requirement.
If this is not possible for you please stick to the old version until 8.2 is officially released

**Comment by sebj54** [comment]
Thanks for the quick reply! 

I forgot about Gradle 7 in this version. I'll close the issue then.
